FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer /app/consumer
COPY .env /app/.env

CMD ["python", "-u", "/app/consumer/consumer.py"]
