FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY worker /app/worker
COPY .env /app/.env

CMD ["celery", "-A", "worker.tasks", "beat", "--loglevel=info"]
